name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ] #, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # Install all the pythons
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      # 3.8 is activated below
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/setup-python@v2
        with:
          python-version: "pypy-3.7"
      - uses: actions/setup-python@v2
        with:
          python-version: "pypy-3.8"
      # Make this the active python
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install virtualenv
        run: |
          pip install -U pip virtualenv
          virtualenv --upgrade-embed-wheels
      - uses: actions-rs/toolchain@v1
        id: rustup
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install hyperfine (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          hyperfine_version="v1.12.0"
          hyperfine_url="https://github.com/sharkdp/hyperfine/releases/download/$hyperfine_version/hyperfine-$hyperfine_version-x86_64-unknown-linux-musl.tar.gz"
          curl -L $hyperfine_url | tar -zxv --strip-components 1 -C $HOME/.local/bin hyperfine-$hyperfine_version-x86_64-unknown-linux-musl/hyperfine
      - name: Install hyperfine (mac)
        if: matrix.os == 'macos-latest'
        run: brew install hyperfine

      # Caching
      # Install gnu-tar because BSD tar is buggy
      # https://github.com/actions/cache/issues/403
      - name: Install GNU tar (Macos)
        if: matrix.os == 'macos-latest'
        run: |
          brew install gnu-tar
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH
      - name: Cache cargo build
        uses: Swatinem/rust-cache@v1
        with:
          key: install-wheel-rs-${{ runner.os }}

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Download pip repo
        run: git clone --depth 1 --branch 22.0.3 -q https://github.com/pypa/pip
      - name: Download popular wheels
        run: pip download -d popular-wheels -r popular.txt

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      # quick test, includes package and console script
      - name: Compare tqdm
        run: python -m test.compare popular-wheels/tqdm-4.62.3-py2.py3-none-any.whl
      - name: Test tqdm
        run: python -m test.test_tqdm

      - name: Test purelib/pathlib
        if: matrix.os == 'ubuntu-latest'
        run: python -m test.compare wheels/purelib_and_platlib-1.0.0-cp38-cp38-linux_x86_64.whl

      - name: Compare pip test wheels
        run: python -m test.test_piptests

      - name: Compare popular wheels
        run: python -m test.test_popular

      - name: Benchmark plotly and tqdm
        if: matrix.os == 'ubuntu-latest'
        run: |
          virtualenv .venv-benchmark
          
          VIRTUAL_ENV=.venv-benchmark hyperfine -r 5 -p ".venv-benchmark/bin/pip uninstall -y plotly" \
            "target/release/install-wheel-rs install-files popular-wheels/plotly-5.5.0-py2.py3-none-any.whl" \
            ".venv-benchmark/bin/pip install --no-deps popular-wheels/plotly-5.5.0-py2.py3-none-any.whl"
          
          VIRTUAL_ENV=.venv-benchmark hyperfine -p ".venv-benchmark/bin/pip uninstall -y tqdm" \
            "target/release/install-wheel-rs install-files popular-wheels/tqdm-4.62.3-py2.py3-none-any.whl" \
            ".venv-benchmark/bin/pip install --no-deps popular-wheels/tqdm-4.62.3-py2.py3-none-any.whl"

          #VIRTUAL_ENV=.venv-benchmark hyperfine -r 5 -p ".venv-benchmark/bin/pip uninstall -y plotly" \
          #  "target/release/install-wheel-rs install-files --no-compile wheels/plotly-5.5.0-py2.py3-none-any.whl" \
          #  ".venv-benchmark/bin/pip install --no-compile --no-deps wheels/plotly-5.5.0-py2.py3-none-any.whl"
          
          rm -r .venv-benchmark
